#title in header
title: "Neverain's Blog"

#main info
#owner
owner: "æ¬¢è¿"
email: me@moqiyu.eu.org
info: "Neverain"
#description
desc: "ä¸€ä¸ªè‡ªç•™åœ°æ€§è´¨çš„åšå®¢ï¼Œä¸»è¦è®°å½•é˜…è¯»å’Œå­¦ä¹ å†ç¨‹ç”¨ã€‚"

#menu
menu:
  æ‰€æœ‰æ–‡ç« : /archives
  # å…³äº: /about
  # å‹é“¾: /links

#index/main page max show posts (in number)
max_post: 5

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Minima
placelink: https://github.com/adisaktijrs/hexo-theme-minima
github: https://github.com/Neverain
# linkedin: https://linkedin.com/in/adisaktijrs
# twitter: https://twitter.com/adisaktijrs
# instagram: https://instagram.com/adisaktijrs
# stackoverflow: https://stackoverflow.com/story/tobiasreithmeier

# Misc
nanobar: /js/nanobar.min.js
switch_light: â˜€ï¸
switch_dark: ğŸŒ‘

# Picture enlargement
picjs: /js/pic.min.js

# favicon
# favicon: /images/favicon.png
# thumbnail
# thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-neverain-github-io
